name: Cloud-Deploy
on:
  push:
    branches: [ main ]
#    # Publish semver tags as releases.
  release:
    types: [published]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21.1'
      - run: go version
      - run: |
          make dep-frontend
          cd frontend
          yarn run build -- --configuration cloud_sandbox --output-path=../dist

      - name: Configure AWS credentials using delegated access
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::410145376638:role/fasten-sandbox-app-gh-frontend-deploy-role
          aws-region: us-east-1

      - name: Copy files to the test website with the AWS CLI
        run: |
          rm -rf dist/index.html
          mv dist/index-cloud.html dist/index.html
          aws s3 sync dist s3://app-sandbox.fastenhealth.com --acl public-read

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: https://app-sandbox.fastenhealth.com/
          environment: sandbox
          initial-status: success

